config/routes.rb
Rails.application.routes.draw do

  resources :meridians
  resources :types
  resources :coach_orders
  resources :days
  resources :sec_lists

  resources :secs

  resources :users
  resources :supervisors
  resources :facilitators
  resources :coaches
  resources :cycles
  resources :roles
  resources :titles
  resources :schools
  resources :emails
  resources :phones

  resources :leaders do
    resources :phones

  end

  resources :trainings do
    resources :menus

  end

  resources :groups do
    resources :leaders

end

end

app/models/coach.rb
class Coach < ActiveRecord::Base
 has_many :schools
 has_one :supervisor

end

app/models/coach_order.rb
class CoachOrder < ActiveRecord::Base
  has_one :supervisor

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_one :group
  has_one :school


  def name_with_id
    "#{id} #{cycle_name}"
  end


end

app/models/day.rb
class Day < ActiveRecord::Base
  has_one :training
end

app/models/email.rb
class Email < ActiveRecord::Base\
 has_one :leader
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :leader

  has_many :groups
  has_many :titles
  has_many :roles
  has_many :secs


end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :schools
  has_many :cycles
  has_many :leaders #:order => desc
  has_many :meridians
  has_many :types


  has_one :facilitator
  has_one :supervisor
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  has_many :phones
  has_many :emails
  has_many :trainings
  has_many  :school

  has_one :facilitators


end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_one :training
end

app/models/meridian.rb
class Meridian < ActiveRecord::Base
  has_one :group

  def name_with_id
    "#{id} #{meridian_name}"
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  has_one :leader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_one :facilitator

end

app/models/school.rb
class School < ActiveRecord::Base
  has_one :leader
  has_one :coach
  has_one :group


  def name_with_id
    "#{id} #{school_name}"
  end


end

app/models/sec.rb
class Sec < ActiveRecord::Base
  has_one :facilitator
end

app/models/sec_list.rb
class SecList < ActiveRecord::Base
  has_one :sec
end

app/models/seniority.rb
class Seniority < ActiveRecord::Base
  has_one :supervisor
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  has_many :groups
  has_many :coaches
  has_many :coach_orders
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_one :facilitator

end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :menus
  has_many :days

end

app/models/type.rb
class Type < ActiveRecord::Base

  has_one :group
  def name_with_id
    "#{id} #{type_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:leader_id, :offering_id, :register, :attended, :day_id, :payment, :certificate, :comments)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :.idealeader_id %><br>
    <%= f.text_field :.idealeader_id %>
  </div>
  <div class="field">
    <%= f.label :offering_id %><br>
    <%= f.number_field :offering_id %>
  </div>
  <div class="field">
    <%= f.label :register %><br>
    <%= f.text_field :register %>
  </div>
  <div class="field">
    <%= f.label :attended %><br>
    <%= f.text_field :attended %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.text_field :payment %>
  </div>
  <div class="field">
    <%= f.label :certificate %><br>
    <%= f.text_field :certificate %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainings</h1>

<table>
  <thead>
    <tr>
      <th>.idealeader</th>
      <th>Offering</th>
      <th>Register</th>
      <th>Attended</th>
      <th>Day</th>
      <th>Payment</th>
      <th>Certificate</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training..idealeader_id %></td>
        <td><%= training.offering_id %></td>
        <td><%= training.register %></td>
        <td><%= training.attended %></td>
        <td><%= training.day %></td>
        <td><%= training.payment %></td>
        <td><%= training.certificate %></td>
        <td><%= training.comments %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>.idealeader:</strong>
  <%= @training..idealeader_id %>
</p>

<p>
  <strong>Offering:</strong>
  <%= @training.offering_id %>
</p>

<p>
  <strong>Register:</strong>
  <%= @training.register %>
</p>

<p>
  <strong>Attended:</strong>
  <%= @training.attended %>
</p>

<p>
  <strong>Day:</strong>
  <%= @training.day %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @training.payment %>
</p>

<p>
  <strong>Certificate:</strong>
  <%= @training.certificate %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @training.comments %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>