config/routes.rb
Rails.application.routes.draw do

  resources :meridians
  resources :types
  resources :coach_orders
  resources :days
  resources :sec_lists

  resources :secs

  resources :users
  resources :supervisors
  resources :facilitators
  resources :coaches
  resources :cycles
  resources :roles
  resources :titles
  resources :schools
  resources :emails
  resources :phones

  resources :leaders do
    resources :phones

  end

  resources :trainings do
    resources :menus

  end

  resources :groups do
    resources :leaders

end

end

app/models/coach.rb
class Coach < ActiveRecord::Base
 has_many :schools
 has_one :supervisor

end

app/models/coach_order.rb
class CoachOrder < ActiveRecord::Base
  has_one :supervisor

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_one :group
  has_one :school


  def name_with_id
    "#{id} #{cycle_name}"
  end


end

app/models/day.rb
class Day < ActiveRecord::Base
  has_one :training
end

app/models/email.rb
class Email < ActiveRecord::Base\
 has_one :leader
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :leader

  has_many :groups
  has_many :titles
  has_many :roles
  has_many :secs


end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :schools
  has_many :cycles
  has_many :leaders #:order => desc
  has_many :meridians
  has_many :types


  has_one :facilitator
  has_one :supervisor
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  has_many :phones
  has_many :emails
  has_many :trainings
  has_many  :school

  has_one :facilitators


end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_one :training
end

app/models/meridian.rb
class Meridian < ActiveRecord::Base
  has_one :group

  def name_with_id
    "#{id} #{meridian_name}"
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  has_one :leader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_one :facilitator

end

app/models/school.rb
class School < ActiveRecord::Base
  has_one :leader
  has_one :coach
  has_one :group


  def name_with_id
    "#{id} #{school_name}"
  end


end

app/models/sec.rb
class Sec < ActiveRecord::Base
  has_one :facilitator
end

app/models/sec_list.rb
class SecList < ActiveRecord::Base
  has_one :sec
end

app/models/seniority.rb
class Seniority < ActiveRecord::Base
  has_one :supervisor
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  has_many :groups
  has_many :coaches
  has_many :coach_orders
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_one :facilitator

end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :menus
  has_many :days

end

app/models/type.rb
class Type < ActiveRecord::Base

  has_one :group
  def name_with_id
    "#{id} #{type_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_gid, :cycle_id, :school_id, :meridian, :type_id, :meridian_id, :comments)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<hr size="4" noshade color="Grey" width="300" align="left">
<div class="actions">
  <%= f.submit %>
</div>
<hr size="3" noshade color="Grey" width="300" align="left">
<table id="table_show_groups" class="display" cellpadding="5" border="1" cellspacing="0" bgcolor="#9370db" frame="box" width="300">
  <thead>
  <tr>
    <th>Data Collection Element</th>
    <th>Answer</th>
  </tr>
  </thead>

  <tbody>

  <tr bgcolor='cccccc'><td><b><%= f.label :id,  		    "DBID"            %></b></td><td>   <b><b><b><%=f.text_field :id                %></td><tr>

  <tr bgcolor="cccccc"><td><b><%= f.label :group_gid,  		"Given Group ID"%></b></td><td>   <b><b><b><%=f.text_field :group_gid          %></td><tr>
  <tr bgcolor="ffffff"><td><b><%= f.label :type_id,         "Group Type ID" %></b></td><td>   <b><b><b><%=f.collection_select(:type_id,      Type.all,       :id,  :name_with_id, :include_blank=>true) %></td><tr>
  <tr bgcolor="ffffff"><td><b><%= f.label :cycle_id,        "Cycle ID"      %></b></td><td>   <b><b><b><%=f.collection_select(:cycle_id,     Cycle.all,      :id,  :name_with_id, :include_blank=>true) %></td><tr>
  <tr bgcolor='cccccc'><td><b><%= f.label :school_id,  		"School ID"     %></b></td><td>   <b><b><b><%=f.collection_select(:school_id,    School.all,     :id,  :name_with_id, :include_blank=>true) %></td><tr>
  <tr bgcolor="ffffff"><td><b><%= f.label :meridian_id,		"AM-PM"         %></b></td><td>   <b><b><b><%=f.collection_select(:meridian_id , Meridian.all,   :id,  :name_with_id, :include_blank=>true) %></td><tr>
  <tr bgcolor="cccccc"><td><b><%= f.label :comments,  		"Comments"      %></b></td><td>   <b><b><b><%=f.text_field :comments          %></td><tr>
  </tbody>
</table>


    <hr size="2" noshade color="Grey" width="300" align="left">

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<hr size="4" noshade color="Grey" width="300" align="left">

<table id="table_show_groups" class="display" cellpadding="5" border="1" cellspacing="0" frame="box" width="300">
  <thead>
  <tr bgcolor="#d3d3d3">

    <th>Given Group Id</th>
      <th>Cycle</th>
      <th>School</th>
      <th>Meridian</th>
  <th style="display:none;">Comments</th>
  <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.group_gid, edit_group_path(group)  %></td>
        <td><%= group.cycle_id %></td>
        <td><%= group.school_id %></td>
        <td><%= group.meridian_id %></td>
        <td><%= group.comments %></td>
        <td><%= link_to 'S', group %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

<hr size="4" noshade color="Grey" width="300" align="left">

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<hr size="4" noshade color="Grey" width="300" align="left">
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>
<hr size="3" noshade color="Grey" width="300" align="left">
<table id="table_show_leaders" class="display" cellpadding="5" border="1" cellspacing="0" bgcolor="#9370db" frame="box"  width="300">
  <tr>
    <th>Data Collection Element</th>
    <th>Answer</th>
  </tr>

  <tr bgcolor='cccccc'><td><b>ID</b></td>	            <td>   <b><%=@group.id    %></b></td></tr>


  <tr bgcolor='cccccc'><td><b>Group ID Given</b></td>	<td>   <b><%=@group.group_gid    %></b></td></tr>
  <tr bgcolor="ffffff"><td><b>Cycle ID:     </b></td>   <td>   <b><%=@group.cycle_id     %></b></td></tr>
  <tr bgcolor='cccccc'><td><b>Last Name</b></td>		<td>   <b><%=@group.school_id    %></b></td></tr>
  <tr bgcolor="ffffff"><td><b>Given Leader ID</b></td>	<td>   <b><%=@group.meridian_id  %></b></td></tr>
  <tr bgcolor='cccccc'><td><b>School ID</b></td>		<td>   <b><%=@group.type_id      %></b></td></tr>
  <tr bgcolor="ffffff"><td><b>Comments</b></td>         <td>   <b><%=@group.comments     %></b></td></tr>
</table>
<hr size="2" noshade color="Grey" width="300" align="left">
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>