config/routes.rb
Rails.application.routes.draw do

  resources :meridians
  resources :types
  resources :coach_orders
  resources :days
  resources :sec_lists

  resources :secs

  resources :users
  resources :supervisors
  resources :facilitators
  resources :coaches
  resources :cycles
  resources :roles
  resources :titles
  resources :schools
  resources :emails
  resources :phones

  resources :leaders do
    resources :phones

  end

  resources :trainings do
    resources :menus

  end

  resources :groups do
    resources :leaders

end

end

app/models/coach.rb
class Coach < ActiveRecord::Base
 has_many :schools
 has_one :supervisor

end

app/models/coach_order.rb
class CoachOrder < ActiveRecord::Base
  has_one :supervisor

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_one :group
  has_one :school


  def name_with_id
    "#{id} #{cycle_name}"
  end


end

app/models/day.rb
class Day < ActiveRecord::Base
  has_one :training
end

app/models/email.rb
class Email < ActiveRecord::Base\
 has_one :leader
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :leader

  has_many :groups
  has_many :titles
  has_many :roles
  has_many :secs


end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :schools
  has_many :cycles
  has_many :leaders #:order => desc
  has_many :meridians
  has_many :types


  has_one :facilitator
  has_one :supervisor
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  has_many :phones
  has_many :emails
  has_many :trainings
  has_many  :school

  has_one :facilitators


end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_one :training
end

app/models/meridian.rb
class Meridian < ActiveRecord::Base
  has_one :group

  def name_with_id
    "#{id} #{meridian_name}"
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  has_one :leader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_one :facilitator

end

app/models/school.rb
class School < ActiveRecord::Base
  has_one :leader
  has_one :coach
  has_one :group


  def name_with_id
    "#{id} #{school_name}"
  end


end

app/models/sec.rb
class Sec < ActiveRecord::Base
  has_one :facilitator
end

app/models/sec_list.rb
class SecList < ActiveRecord::Base
  has_one :sec
end

app/models/seniority.rb
class Seniority < ActiveRecord::Base
  has_one :supervisor
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  has_many :groups
  has_many :coaches
  has_many :coach_orders
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_one :facilitator

end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :menus
  has_many :days

end

app/models/type.rb
class Type < ActiveRecord::Base

  has_one :group
  def name_with_id
    "#{id} #{type_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/meridians_controller.rb
class MeridiansController < ApplicationController
  before_action :set_meridian, only: [:show, :edit, :update, :destroy]

  # GET /meridians
  # GET /meridians.json
  def index
    @meridians = Meridian.all
  end

  # GET /meridians/1
  # GET /meridians/1.json
  def show
  end

  # GET /meridians/new
  def new
    @meridian = Meridian.new
  end

  # GET /meridians/1/edit
  def edit
  end

  # POST /meridians
  # POST /meridians.json
  def create
    @meridian = Meridian.new(meridian_params)

    respond_to do |format|
      if @meridian.save
        format.html { redirect_to @meridian, notice: 'Meridian was successfully created.' }
        format.json { render :show, status: :created, location: @meridian }
      else
        format.html { render :new }
        format.json { render json: @meridian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meridians/1
  # PATCH/PUT /meridians/1.json
  def update
    respond_to do |format|
      if @meridian.update(meridian_params)
        format.html { redirect_to @meridian, notice: 'Meridian was successfully updated.' }
        format.json { render :show, status: :ok, location: @meridian }
      else
        format.html { render :edit }
        format.json { render json: @meridian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meridians/1
  # DELETE /meridians/1.json
  def destroy
    @meridian.destroy
    respond_to do |format|
      format.html { redirect_to meridians_url, notice: 'Meridian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meridian
      @meridian = Meridian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meridian_params
      params.require(:meridian).permit(:meridian_name, :comments)
    end
end

app/helpers/meridians_helper.rb
module MeridiansHelper
end

app/views/meridians/_form.html.erb
<%= form_for(@meridian) do |f| %>
  <% if @meridian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meridian.errors.count, "error") %> prohibited this meridian from being saved:</h2>

      <ul>
      <% @meridian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meridian_name %><br>
    <%= f.text_field :meridian_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meridians/edit.html.erb
<h1>Editing Meridian</h1>

<%= render 'form' %>

<%= link_to 'Show', @meridian %> |
<%= link_to 'Back', meridians_path %>

app/views/meridians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meridians</h1>

<table>
  <thead>
    <tr>
      <th>Meridian name</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meridians.each do |meridian| %>
      <tr>
        <td><%= meridian.meridian_name %></td>
        <td><%= meridian.comments %></td>
        <td><%= link_to 'Show', meridian %></td>
        <td><%= link_to 'Edit', edit_meridian_path(meridian) %></td>
        <td><%= link_to 'Destroy', meridian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meridian', new_meridian_path %>

app/views/meridians/new.html.erb
<h1>New Meridian</h1>

<%= render 'form' %>

<%= link_to 'Back', meridians_path %>

app/views/meridians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meridian name:</strong>
  <%= @meridian.meridian_name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @meridian.comments %>
</p>

<%= link_to 'Edit', edit_meridian_path(@meridian) %> |
<%= link_to 'Back', meridians_path %>