config/routes.rb
Rails.application.routes.draw do

  resources :meridians
  resources :types
  resources :coach_orders
  resources :days
  resources :sec_lists

  resources :secs

  resources :users
  resources :supervisors
  resources :facilitators
  resources :coaches
  resources :cycles
  resources :roles
  resources :titles
  resources :schools
  resources :emails
  resources :phones

  resources :leaders do
    resources :phones

  end

  resources :trainings do
    resources :menus

  end

  resources :groups do
    resources :leaders

end

end

app/models/coach.rb
class Coach < ActiveRecord::Base
 has_many :schools
 has_one :supervisor

end

app/models/coach_order.rb
class CoachOrder < ActiveRecord::Base
  has_one :supervisor

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_one :group
  has_one :school


  def name_with_id
    "#{id} #{cycle_name}"
  end


end

app/models/day.rb
class Day < ActiveRecord::Base
  has_one :training
end

app/models/email.rb
class Email < ActiveRecord::Base\
 has_one :leader
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :leader

  has_many :groups
  has_many :titles
  has_many :roles
  has_many :secs


end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :schools
  has_many :cycles
  has_many :leaders #:order => desc
  has_many :meridians
  has_many :types


  has_one :facilitator
  has_one :supervisor
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  has_many :phones
  has_many :emails
  has_many :trainings
  has_many  :school

  has_one :facilitators


end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_one :training
end

app/models/meridian.rb
class Meridian < ActiveRecord::Base
  has_one :group

  def name_with_id
    "#{id} #{meridian_name}"
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  has_one :leader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_one :facilitator

end

app/models/school.rb
class School < ActiveRecord::Base
  has_one :leader
  has_one :coach
  has_one :group


  def name_with_id
    "#{id} #{school_name}"
  end


end

app/models/sec.rb
class Sec < ActiveRecord::Base
  has_one :facilitator
end

app/models/sec_list.rb
class SecList < ActiveRecord::Base
  has_one :sec
end

app/models/seniority.rb
class Seniority < ActiveRecord::Base
  has_one :supervisor
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  has_many :groups
  has_many :coaches
  has_many :coach_orders
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_one :facilitator

end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :menus
  has_many :days

end

app/models/type.rb
class Type < ActiveRecord::Base

  has_one :group
  def name_with_id
    "#{id} #{type_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/sec_lists_controller.rb
class SecListsController < ApplicationController
  before_action :set_sec_list, only: [:show, :edit, :update, :destroy]

  # GET /sec_lists
  # GET /sec_lists.json
  def index
    @sec_lists = SecList.all
  end

  # GET /sec_lists/1
  # GET /sec_lists/1.json
  def show
  end

  # GET /sec_lists/new
  def new
    @sec_list = SecList.new
  end

  # GET /sec_lists/1/edit
  def edit
  end

  # POST /sec_lists
  # POST /sec_lists.json
  def create
    @sec_list = SecList.new(sec_list_params)

    respond_to do |format|
      if @sec_list.save
        format.html { redirect_to @sec_list, notice: 'Sec list was successfully created.' }
        format.json { render :show, status: :created, location: @sec_list }
      else
        format.html { render :new }
        format.json { render json: @sec_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sec_lists/1
  # PATCH/PUT /sec_lists/1.json
  def update
    respond_to do |format|
      if @sec_list.update(sec_list_params)
        format.html { redirect_to @sec_list, notice: 'Sec list was successfully updated.' }
        format.json { render :show, status: :ok, location: @sec_list }
      else
        format.html { render :edit }
        format.json { render json: @sec_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sec_lists/1
  # DELETE /sec_lists/1.json
  def destroy
    @sec_list.destroy
    respond_to do |format|
      format.html { redirect_to sec_lists_url, notice: 'Sec list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sec_list
      @sec_list = SecList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sec_list_params
      params.require(:sec_list).permit(:number)
    end
end

app/helpers/sec_lists_helper.rb
module SecListsHelper
end

app/views/sec_lists/_form.html.erb
<%= form_for(@sec_list) do |f| %>
  <% if @sec_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sec_list.errors.count, "error") %> prohibited this sec_list from being saved:</h2>

      <ul>
      <% @sec_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :.ideanumber %><br>
    <%= f.number_field :.ideanumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sec_lists/edit.html.erb
<h1>Editing Sec List</h1>

<%= render 'form' %>

<%= link_to 'Show', @sec_list %> |
<%= link_to 'Back', sec_lists_path %>

app/views/sec_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sec Lists</h1>

<table>
  <thead>
    <tr>
      <th>.ideanumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sec_lists.each do |sec_list| %>
      <tr>
        <td><%= sec_list..ideanumber %></td>
        <td><%= link_to 'Show', sec_list %></td>
        <td><%= link_to 'Edit', edit_sec_list_path(sec_list) %></td>
        <td><%= link_to 'Destroy', sec_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sec list', new_sec_list_path %>

app/views/sec_lists/new.html.erb
<h1>New Sec List</h1>

<%= render 'form' %>

<%= link_to 'Back', sec_lists_path %>

app/views/sec_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>.ideanumber:</strong>
  <%= @sec_list..ideanumber %>
</p>

<%= link_to 'Edit', edit_sec_list_path(@sec_list) %> |
<%= link_to 'Back', sec_lists_path %>